import type { Pack } from '../packs';

/** Pack 4: everything at once, with very little room. Every one has been solved. */
export const IMPOSSIBLE: Pack = {
  id: 'impossible',
  name: 'Impossible?',
  idea: 'All of it, precisely',
  blurb: 'Tiny windows, wild worlds. Every one of these has been solved.',
  colour: '#b58cff',
  puzzles: [
    {
      id: 'moonshot',
      name: 'Moonshot',
      brief: 'The Moon. A tower that scrapes the sky. A pad at the far end.',
      hint: 'In lunar gravity one step of power goes a long way: steer with the angle instead.',
      world: 'moon',
      wind: 0,
      city: {
        seed: 401,
        blocks: [
          [70, 150],
          [72, 115],
          [68, 125],
          [74, 110],
          [66, 290],
          [72, 130],
          [70, 105],
          [66, 120],
          [58, 100],
        ],
      },
      stand: { on: 0 },
      targets: [{ kind: 'pad', on: 8 }],
      par: 8,
      style: { kind: 'bullseye', metres: 0.5 },
      solution: { angle: 47.5, velocity: 29 },
      timeOfDay: 1,
    },
    {
      id: 'needles-eye',
      name: 'Needle’s Eye',
      brief: 'Skim the hoop between the rooftop and the billboard, then break the crate.',
      hint: 'The slot is flat: top out your arc right at the hoop.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 402,
        blocks: [
          [76, 110],
          [78, 130],
          [74, 105],
          [80, 185],
          [76, 95],
          [78, 105],
          [76, 115],
          [80, 100],
        ],
      },
      stand: { on: 1 },
      targets: [
        { kind: 'hoop', x: 276, y: 134 },
        { kind: 'crate', on: 5 },
      ],
      hazards: {
        drone: { from: 276, to: 276, y: 112, width: 70, height: 10, phase: 0, speed: 0 },
      },
      par: 8,
      style: { kind: 'bullseye', metres: 0.65 },
      solution: { angle: 30, velocity: 55 },
      timeOfDay: 0.7,
    },
    {
      id: 'eye-of-the-storm',
      name: 'Eye of the Storm',
      brief: 'Jupiter: a gale against you below, a jet stream with you above. Ring the bell.',
      hint: 'Too low and the gale eats it; too high and the jet stream flings it past.',
      world: 'jupiter',
      wind: -9,
      city: {
        seed: 403,
        blocks: [
          [70, 150],
          [72, 115],
          [68, 125],
          [74, 110],
          [66, 180],
          [72, 130],
          [70, 105],
          [66, 150],
          [58, 100],
        ],
      },
      stand: { on: 0 },
      targets: [{ kind: 'bell', on: 7 }],
      hazards: { jetStream: { top: 28, bottom: 72, wind: 20 } },
      par: 8,
      style: { kind: 'quick', seconds: 2 },
      solution: { angle: 30, velocity: 120 },
      timeOfDay: 0.5,
    },
    {
      id: 'sunburst',
      name: 'Sunburst',
      brief: 'A Tri-Banana through the sun, and three crates to break.',
      hint: 'Mars’s low gravity makes a wide fan. Split it right in the sun.',
      world: 'mars',
      wind: 0,
      city: {
        seed: 404,
        blocks: [
          [76, 110],
          [78, 125],
          [74, 105],
          [80, 115],
          [76, 100],
          [78, 110],
          [76, 95],
          [80, 105],
        ],
      },
      stand: { on: 1 },
      targets: [
        { kind: 'crate', on: 6, along: 0.84 },
        { kind: 'crate', on: 7, along: 0.16 },
        { kind: 'crate', on: 7, along: 0.5 },
      ],
      powerUp: 'tri',
      par: 8,
      style: { kind: 'sun' },
      solution: { angle: 55, velocity: 41 },
      timeOfDay: 0.4,
    },
    {
      id: 'drone-dodger',
      name: 'Drone Dodger',
      brief: 'A billboard drone sweeps the sky between you. Time your throw.',
      hint: 'The drone only moves while a banana flies. Where will it be when yours arrives?',
      world: 'earth',
      wind: 3,
      city: {
        seed: 405,
        blocks: [
          [76, 110],
          [78, 125],
          [74, 105],
          [80, 115],
          [76, 100],
          [78, 110],
          [76, 120],
          [80, 105],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'dummy', on: 6 }],
      hazards: {
        drone: { from: 380, to: 560, y: 165, width: 44, height: 14, phase: 0.5, speed: 1 / 30 },
      },
      par: 8,
      style: { kind: 'bonk' },
      solution: { angle: 55, velocity: 61 },
      timeOfDay: 1.2,
    },
    {
      id: 'impossible',
      name: 'Impossible?',
      brief: 'Backwards, into a hurricane, off a wall and through a hoop to ring the bell.',
      hint: 'Throw back over your shoulder; the wind turns it round and the wall sends it home.',
      world: 'earth',
      wind: 14,
      city: {
        seed: 406,
        blocks: [
          [76, 110],
          [78, 120],
          [50, 250],
          [100, 90],
          [60, 270],
          [78, 105],
          [80, 120],
          [80, 100],
        ],
      },
      stand: { on: 1 },
      targets: [
        { kind: 'hoop', x: 280, y: 180 },
        { kind: 'bell', on: 3, along: 0.4 },
      ],
      powerUp: 'bouncer',
      par: 10,
      style: { kind: 'sky' },
      solution: { angle: 95, velocity: 78 },
      timeOfDay: 1,
    },
  ],
};
