import type { Pack } from '../packs';

/** Pack 3: throws that do more than fly. Hoops, the sun, bounces, splits and golden blasts. */
export const TRICK_ARCS: Pack = {
  id: 'trick-arcs',
  name: 'Trick Arcs',
  idea: 'Shaping the throw',
  blurb: 'Through hoops, off walls, into three. Bananas can do more than fly.',
  colour: '#ff6fd8',
  puzzles: [
    {
      id: 'hoop-dreams',
      name: 'Hoop Dreams',
      brief: 'Fly through the hoop, then break the crate.',
      hint: 'The hoop does not stop the banana: aim through it as if it were not there.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 301,
        blocks: [
          [76, 110],
          [78, 125],
          [74, 100],
          [80, 150],
          [76, 105],
          [78, 115],
          [76, 95],
          [80, 105],
        ],
      },
      stand: { on: 1 },
      targets: [
        { kind: 'hoop', x: 320, y: 86 },
        { kind: 'crate', on: 6 },
      ],
      par: 4,
      style: { kind: 'bullseye', metres: 0.65 },
      solution: { angle: 45, velocity: 59 },
      timeOfDay: 1,
    },
    {
      id: 'here-comes-the-sun',
      name: 'Here Comes the Sun',
      brief: 'Hit the dummy, but only after your banana passes through the sun.',
      hint: 'The sun is halfway across: an arc that tops out there comes down on the far side.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 302,
        blocks: [
          [76, 105],
          [78, 120],
          [74, 110],
          [80, 95],
          [76, 115],
          [78, 100],
          [76, 125],
          [80, 105],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'dummy', on: 6 }],
      rule: 'sun',
      par: 5,
      style: { kind: 'bonk' },
      solution: { angle: 57.5, velocity: 66 },
      timeOfDay: 1.1,
    },
    {
      id: 'bank-shot',
      name: 'Bank Shot',
      brief: 'The Bouncer bounces once. Bank it off the tall wall onto the crate.',
      hint: 'Hit the far tower low and hard: the banana comes back off the wall.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 303,
        blocks: [
          [76, 110],
          [78, 125],
          [74, 100],
          [80, 215],
          [90, 65],
          [64, 245],
          [76, 110],
          [80, 105],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'crate', on: 4, along: 0.15 }],
      powerUp: 'bouncer',
      par: 5,
      style: { kind: 'quick', seconds: 3.5 },
      solution: { angle: 40, velocity: 56 },
      timeOfDay: 1.2,
    },
    {
      id: 'three-for-three',
      name: 'Three for Three',
      brief: 'A Tri-Banana splits at the top of its arc. Land all three on the pad.',
      hint: 'The three fan out as they fall: a lower split keeps the fan tight.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 304,
        blocks: [
          [76, 110],
          [78, 125],
          [74, 105],
          [80, 115],
          [76, 100],
          [78, 110],
          [76, 95],
          [80, 105],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'pad', on: 5 }],
      rule: 'allBananas',
      powerUp: 'tri',
      par: 6,
      style: { kind: 'sky' },
      solution: { angle: 75, velocity: 79 },
      timeOfDay: 0.9,
    },
    {
      id: 'double-bounce',
      name: 'Double Bounce',
      brief: 'Springy roofs and a Bouncer: two bounces, then the bell.',
      hint: 'Each bounce keeps three quarters of the speed. Start low and fast.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 305,
        blocks: [
          [76, 110],
          [78, 125],
          [74, 90],
          [80, 90],
          [76, 90],
          [78, 90],
          [76, 90],
          [80, 120],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'bell', on: 7 }],
      rule: 'bounceTwice',
      powerUp: 'bouncer',
      hazards: { bouncy: true },
      par: 6,
      style: { kind: 'sky' },
      solution: { angle: 80, velocity: 83 },
      timeOfDay: 0.8,
    },
    {
      id: 'golden-touch',
      name: 'Golden Touch',
      brief: 'The dummy hides behind a tower. The Golden Banana does not need a direct hit.',
      hint: 'A golden blast on the dummy’s roof knocks the whole roof section off.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 306,
        blocks: [
          [76, 110],
          [78, 125],
          [74, 100],
          [70, 110],
          [60, 175],
          [110, 100],
          [76, 115],
          [70, 105],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'dummy', on: 5 }],
      powerUp: 'golden',
      hazards: {
        drone: { from: 432, to: 432, y: 190, width: 30, height: 8, phase: 0, speed: 0 },
      },
      par: 5,
      style: { kind: 'sun' },
      solution: { angle: 70, velocity: 65 },
      timeOfDay: 1.3,
    },
  ],
};
