import type { Pack } from '../packs';

/** Pack 1: how angle and power shape a throw, with no wind to worry about. */
export const WARM_UP: Pack = {
  id: 'warm-up',
  name: 'Warm-up',
  idea: 'Angle and power',
  blurb: 'No wind, no tricks: just you, a banana and gravity.',
  colour: '#ffb03d',
  puzzles: [
    {
      id: 'first-toss',
      name: 'First Toss',
      brief: 'Hit the dummy. Drag back from your gorilla to aim, or use the arrows and Space.',
      hint: 'The dummy is level with you, and 45° carries furthest for your power.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 101,
        blocks: [
          [76, 110],
          [78, 125],
          [74, 95],
          [80, 105],
          [76, 110],
          [78, 115],
          [76, 130],
          [80, 100],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'dummy', on: 4 }],
      par: 4,
      style: { kind: 'bonk' },
      solution: { angle: 45, velocity: 47 },
      timeOfDay: 0.1,
    },
    {
      id: 'over-the-top',
      name: 'Over the Top',
      brief: 'A tower stands in the way. Get over it.',
      hint: 'Raise the angle. Steeper throws need more power to go the same distance.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 102,
        blocks: [
          [76, 115],
          [78, 120],
          [74, 100],
          [80, 245],
          [76, 105],
          [78, 120],
          [76, 110],
          [80, 100],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'dummy', on: 5 }],
      par: 4,
      style: { kind: 'sky' },
      solution: { angle: 82.5, velocity: 111 },
      timeOfDay: 0.2,
    },
    {
      id: 'special-delivery',
      name: 'Special Delivery',
      brief: 'Knock the crate off the far roof.',
      hint: 'A lower angle and more power gets there faster.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 103,
        blocks: [
          [80, 140],
          [76, 100],
          [78, 95],
          [74, 110],
          [80, 105],
          [76, 150],
          [78, 120],
          [76, 100],
        ],
      },
      stand: { on: 0 },
      targets: [{ kind: 'crate', on: 5, along: 0.5 }],
      par: 4,
      style: { kind: 'quick', seconds: 2 },
      solution: { angle: 15, velocity: 83 },
      timeOfDay: 0.3,
    },
    {
      id: 'down-the-chimney',
      name: 'Down the Chimney',
      brief: 'The crate sits deep between two towers. Drop the banana straight in.',
      hint: 'Throw high and gently, so it falls almost straight down.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 104,
        blocks: [
          [70, 120],
          [72, 130],
          [66, 110],
          [70, 190],
          [56, 60],
          [70, 190],
          [68, 115],
          [70, 120],
          [70, 110],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'crate', on: 4 }],
      par: 5,
      style: { kind: 'bullseye', metres: 0.65 },
      solution: { angle: 80, velocity: 76 },
      timeOfDay: 0.4,
    },
    {
      id: 'ring-the-bell',
      name: 'Ring the Bell',
      brief: 'Ring the bell on the tall roof.',
      hint: 'A small target: nudge the power one step at a time.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 105,
        blocks: [
          [76, 100],
          [78, 120],
          [74, 180],
          [80, 130],
          [76, 160],
          [78, 120],
          [76, 170],
          [80, 110],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'bell', on: 6, along: 0.5 }],
      par: 5,
      style: { kind: 'sun' },
      solution: { angle: 55, velocity: 66 },
      timeOfDay: 0.5,
    },
    {
      id: 'long-bomb',
      name: 'Long Bomb',
      brief: 'Land on the pad at the far end of the city.',
      hint: 'Hold Shift (or LB) to fine-tune the power a tenth at a time.',
      world: 'earth',
      wind: 0,
      city: {
        seed: 106,
        blocks: [
          [70, 150],
          [72, 120],
          [68, 140],
          [74, 110],
          [66, 135],
          [72, 105],
          [70, 125],
          [66, 115],
          [58, 95],
        ],
      },
      stand: { on: 0 },
      targets: [{ kind: 'pad', on: 8 }],
      par: 6,
      style: { kind: 'bullseye', metres: 1 },
      solution: { angle: 45, velocity: 70 },
      timeOfDay: 0.6,
    },
  ],
};
