import type { Pack } from '../packs';

/** Pack 2: reading the air. The wind gauge, then winds that are not on the gauge at all. */
export const WIND_READERS: Pack = {
  id: 'wind-readers',
  name: 'Wind Readers',
  idea: 'Reading the wind',
  blurb: 'Every banana drifts. Learn which way, and how far.',
  colour: '#5fd4ff',
  puzzles: [
    {
      id: 'headwind',
      name: 'Headwind',
      brief: 'The wind blows straight at you. Hit the dummy anyway.',
      hint: 'The wind pushes back all the way: throw harder than you would in calm air.',
      world: 'earth',
      wind: -6,
      city: {
        seed: 201,
        blocks: [
          [76, 105],
          [78, 125],
          [74, 100],
          [80, 115],
          [76, 95],
          [78, 120],
          [76, 110],
          [80, 100],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'dummy', on: 5 }],
      par: 4,
      style: { kind: 'quick', seconds: 2.2 },
      solution: { angle: 20, velocity: 67 },
      timeOfDay: 2.2,
    },
    {
      id: 'tailwind',
      name: 'Tailwind',
      brief: 'A strong wind at your back. Land on the pad, not past it.',
      hint: 'The longer it flies, the further the wind carries it: ease off, or throw flatter.',
      world: 'earth',
      wind: 9,
      city: {
        seed: 202,
        blocks: [
          [76, 110],
          [78, 130],
          [74, 105],
          [80, 95],
          [76, 115],
          [78, 100],
          [76, 125],
          [80, 105],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'pad', on: 5 }],
      par: 5,
      style: { kind: 'bullseye', metres: 1 },
      solution: { angle: 45, velocity: 46 },
      timeOfDay: 2.3,
    },
    {
      id: 'heavy-weather',
      name: 'Heavy Weather',
      brief: 'Jupiter: crushing gravity and a gale in your face. Break the crate.',
      hint: 'Everything falls fast here, so throw hard; the gale takes more off a slow lob.',
      world: 'jupiter',
      wind: -10,
      city: {
        seed: 203,
        blocks: [
          [80, 120],
          [76, 140],
          [78, 105],
          [74, 115],
          [80, 100],
          [76, 125],
          [78, 110],
          [76, 95],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'crate', on: 5 }],
      par: 5,
      style: { kind: 'quick', seconds: 1.5 },
      solution: { angle: 20, velocity: 99 },
      timeOfDay: 2.4,
    },
    {
      id: 'jet-stream',
      name: 'Jet Stream',
      brief: 'Down here the wind is against you. Up there, it is not.',
      hint: 'The band of fast air near the top blows the other way: lob up into it.',
      world: 'earth',
      wind: -5,
      city: {
        seed: 204,
        blocks: [
          [70, 150],
          [72, 115],
          [68, 125],
          [74, 180],
          [66, 255],
          [72, 130],
          [70, 105],
          [66, 120],
          [58, 100],
        ],
      },
      stand: { on: 0 },
      targets: [{ kind: 'pad', on: 8 }],
      hazards: { jetStream: { top: 28, bottom: 72, wind: 18 } },
      par: 5,
      style: { kind: 'bullseye', metres: 1.5 },
      solution: { angle: 60, velocity: 82 },
      timeOfDay: 2.5,
    },
    {
      id: 'dust-devil',
      name: 'Dust Devil',
      brief: 'A whirlwind spins between you and the dummy on Mars.',
      hint: 'The whirlwind shoves anything inside it back towards you. Go over its top.',
      world: 'mars',
      wind: 2,
      city: {
        seed: 205,
        blocks: [
          [76, 110],
          [78, 120],
          [74, 95],
          [80, 105],
          [76, 100],
          [78, 115],
          [76, 125],
          [80, 105],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'dummy', on: 6 }],
      hazards: { dustDevil: { x: 330, width: 44, top: 70, push: -4 } },
      par: 5,
      style: { kind: 'bonk' },
      solution: { angle: 20, velocity: 48 },
      timeOfDay: 2.6,
    },
    {
      id: 'boomerang',
      name: 'Boomerang',
      brief: 'A tower right beside you, a crate right behind it, and a hurricane at your back.',
      hint: 'Throw almost straight up, or even backwards: the wind will bring it round.',
      world: 'earth',
      wind: 12,
      city: {
        seed: 206,
        blocks: [
          [76, 110],
          [78, 120],
          [50, 250],
          [100, 90],
          [76, 115],
          [78, 105],
          [80, 120],
          [80, 100],
        ],
      },
      stand: { on: 1 },
      targets: [{ kind: 'crate', on: 3 }],
      par: 6,
      style: { kind: 'bullseye', metres: 0.65 },
      solution: { angle: 100, velocity: 101 },
      timeOfDay: 2.7,
    },
  ],
};
