import { definePassManifest, glyphs } from '@shared/pass/manifest';

/**
 * A pretend game for the Pass Lab: every tier, counted badges, secrets and
 * cosmetics, so the Hall's cabinet and the toasts can be seen in every state
 * before a real game joins. Loaded by the dev server only.
 */
export default definePassManifest({
  game: 'pass-lab',
  badges: [
    {
      id: 'first-coin',
      name: 'First Coin',
      description: 'Dropped your first coin in the slot. The machine hums with approval.',
      hint: 'Play any round.',
      tier: 'bronze',
      emblem: glyphs.coin,
    },
    {
      id: 'warmed-up',
      name: 'Warmed Up',
      description: 'Ten rounds in, fingers loose, eyes sharp.',
      hint: 'Play 10 rounds.',
      tier: 'bronze',
      target: 10,
      emblem: glyphs.flame,
    },
    {
      id: 'bullseye',
      name: 'Bullseye',
      description: 'Dead centre. Somebody take a picture.',
      hint: 'Hit the exact middle of a target.',
      tier: 'bronze',
      emblem: glyphs.target,
    },
    {
      id: 'night-owl',
      name: 'Night Owl',
      description: 'Played past midnight. The arcade never closes for you.',
      hint: 'Play a round after midnight.',
      tier: 'bronze',
      emblem: glyphs.moon,
    },
    {
      id: 'sprinter',
      name: 'Sprinter',
      description: 'Won in under a minute. Blink and you missed it.',
      hint: 'Win a round in under 60 seconds.',
      tier: 'bronze',
      emblem: glyphs.clock,
    },
    {
      id: 'magpie',
      name: 'Magpie',
      description: 'Twenty-five power-ups, all of them shiny.',
      hint: 'Collect 25 power-ups.',
      tier: 'bronze',
      target: 25,
      emblem: glyphs.gem,
    },
    {
      id: 'hot-streak',
      name: 'Hot Streak',
      description: 'Five wins in a row. Careful, the machine is warming up too.',
      hint: 'Win 5 rounds in a row.',
      tier: 'silver',
      emblem: glyphs.bolt,
    },
    {
      id: 'globetrotter',
      name: 'Globetrotter',
      description: 'Played on every world. Your passport is mostly stamps now.',
      hint: 'Play a round on every world.',
      tier: 'silver',
      emblem: glyphs.planet,
    },
    {
      id: 'flawless',
      name: 'Flawless',
      description: 'Won without taking a single hit.',
      hint: 'Win a match without being hit.',
      tier: 'silver',
      emblem: glyphs.shield,
    },
    {
      id: 'marathon',
      name: 'Marathon',
      description: 'One hundred rounds. Hydrate.',
      hint: 'Play 100 rounds.',
      tier: 'silver',
      target: 100,
      emblem: glyphs.hourglass,
    },
    {
      id: 'lift-off',
      name: 'Lift-off',
      description: 'Sent something clean off the top of the screen.',
      hint: 'Leave the screen through the top.',
      tier: 'silver',
      emblem: glyphs.rocket,
    },
    {
      id: 'champion',
      name: 'Champion',
      description: 'Beat the final boss. The crowd goes quietly, respectfully wild.',
      hint: 'Beat the final boss.',
      tier: 'gold',
      emblem: glyphs.trophy,
    },
    {
      id: 'untouchable',
      name: 'Untouchable',
      description: 'Ten wins in a row. Nobody could lay a finger on you.',
      hint: 'Win 10 rounds in a row.',
      tier: 'gold',
      emblem: glyphs.crown,
    },
    {
      id: 'curator',
      name: 'Curator',
      description: 'Every other badge on this shelf, earned. A true collector.',
      hint: 'Earn every other Pass Lab badge.',
      tier: 'gold',
      xp: 250,
      emblem: glyphs.medal,
    },
    {
      id: 'oops',
      name: 'Oops',
      description: 'Hit yourself. Physics sends its regards.',
      tier: 'secret',
      emblem: glyphs.skull,
    },
    {
      id: 'staring-contest',
      name: 'Staring Contest',
      description: 'Stood perfectly still for five minutes. The game blinked first.',
      tier: 'secret',
      emblem: glyphs.eye,
    },
    {
      id: 'lucky-seven',
      name: 'Lucky Seven',
      description: 'Won seven rounds on the seventh day. Coincidence? Absolutely.',
      tier: 'secret',
      emblem: glyphs.dice,
    },
    {
      id: 'sun-worshipper',
      name: 'Sun Worshipper',
      description: 'Hit the sun three times in one round. It has filed a complaint.',
      tier: 'secret',
      emblem: glyphs.sun,
    },
  ],
  cosmetics: [
    { id: 'safety-goggles', name: 'Safety goggles', kind: 'Eyewear', unlock: { level: 3 } },
    { id: 'neon-trail', name: 'Neon trail', kind: 'Trail', unlock: { level: 8 } },
    { id: 'lab-coat', name: 'Lab coat', kind: 'Outfit', unlock: { badge: 'champion' } },
    { id: 'rubber-duck', name: 'Rubber duck', kind: 'Mascot', unlock: { badge: 'oops' } },
  ],
  stats: [
    { key: 'rounds', label: 'Rounds played' },
    { key: 'wins', label: 'Rounds won' },
    { key: 'bestStreak', label: 'Best streak' },
    { key: 'fastestWin', label: 'Fastest win', unit: 's' },
    { key: 'sunHits', label: 'Sun hits' },
  ],
});
