import type { RegionId } from '../data/regions';
import type { FarLayer } from './horizon';
import type { SceneryKind } from './scenery';

/**
 * How each region looks from the road, in daylight colours: the far
 * horizon, what stands in the fields, and what lines the roadside. The side
 * view and the cab view both read these.
 */
export type NearKind = 'fence' | 'poles' | 'rail' | 'posts' | 'grass' | 'rocks' | 'board-fence';

export interface Landscape {
  ground: string;
  /** The ground near the horizon, usually paler. */
  groundFar: string;
  shoulder: string;
  far: readonly Omit<FarLayer, 'seed'>[];
  mid: readonly (readonly [SceneryKind, number])[];
  /** Mid-distance things per thousand pixels. */
  midDensity: number;
  near: readonly NearKind[];
  /** Snow lies here in winter even on a clear day. */
  snowyWinter: boolean;
}

const far = (
  kind: FarLayer['kind'],
  colour: string,
  height: number,
  depth: number,
  snow = false,
): Omit<FarLayer, 'seed'> => ({ kind, colour, height, depth, snow });

export const LANDSCAPES: Readonly<Record<RegionId, Landscape>> = {
  'la-basin': {
    ground: '#b9a774',
    groundFar: '#c9b98c',
    shoulder: '#a99a74',
    far: [far('mountains', '#8f8aa0', 0.55, 0.9), far('hills', '#8b8a64', 0.28, 0.4)],
    mid: [
      ['fan-palm', 4],
      ['oak', 2],
      ['billboard', 2],
      ['farmhouse', 1],
    ],
    midDensity: 6,
    near: ['poles', 'rail'],
    snowyWinter: false,
  },
  mojave: {
    ground: '#d6bf8d',
    groundFar: '#e2cfa3',
    shoulder: '#c4ad7d',
    far: [far('mountains', '#a8917e', 0.42, 0.75)],
    mid: [
      ['joshua', 4],
      ['creosote', 6],
      ['rock', 1],
      ['billboard', 1],
    ],
    midDensity: 6,
    near: ['posts', 'rocks'],
    snowyWinter: false,
  },
  sonoran: {
    ground: '#c9a77a',
    groundFar: '#d8bb92',
    shoulder: '#b8986c',
    far: [far('mountains', '#8f6f78', 0.48, 0.7)],
    mid: [
      ['saguaro', 6],
      ['ocotillo', 2],
      ['creosote', 4],
      ['rock', 1],
    ],
    midDensity: 6,
    near: ['posts', 'rocks'],
    snowyWinter: false,
  },
  ponderosa: {
    ground: '#6f7a4c',
    groundFar: '#7f8a5c',
    shoulder: '#8a7d62',
    far: [far('volcano', '#7d84a2', 0.75, 0.85, true), far('ridges', '#4f6a48', 0.25, 0.3)],
    mid: [
      ['ponderosa', 9],
      ['rock', 1],
    ],
    midDensity: 9,
    near: ['poles', 'rail'],
    snowyWinter: true,
  },
  mesas: {
    ground: '#c98b5e',
    groundFar: '#d8a074',
    shoulder: '#b98060',
    far: [far('mesas', '#b0644a', 0.5, 0.7), far('buttes', '#a35a42', 0.3, 0.35)],
    mid: [
      ['sage', 5],
      ['mesquite', 2],
      ['rock', 2],
      ['spire', 1],
    ],
    midDensity: 5,
    near: ['fence', 'rocks'],
    snowyWinter: false,
  },
  'high-plains': {
    ground: '#c3b27c',
    groundFar: '#cfc093',
    shoulder: '#b3a273',
    far: [far('mountains', '#7d86a3', 0.38, 0.85, true)],
    mid: [
      ['yucca', 4],
      ['sage', 5],
      ['windmill', 1],
      ['cattle', 1],
    ],
    midDensity: 5,
    near: ['fence', 'poles'],
    snowyWinter: false,
  },
  'west-texas': {
    ground: '#c6ae80',
    groundFar: '#d2bd94',
    shoulder: '#b49d71',
    far: [far('buttes', '#a08a70', 0.2, 0.7)],
    mid: [
      ['pumpjack', 4],
      ['creosote', 5],
      ['mesquite', 2],
      ['derrick', 1],
      ['water-tower', 1],
    ],
    midDensity: 6,
    near: ['fence', 'poles'],
    snowyWinter: false,
  },
  panhandle: {
    ground: '#c8b47e',
    groundFar: '#d6c495',
    shoulder: '#b8a372',
    far: [far('flat', '#a49870', 0.06, 0.8)],
    mid: [
      ['windmill', 2],
      ['elevator', 2],
      ['cattle', 3],
      ['haybale', 1],
      ['wheat', 3],
      ['water-tower', 1],
    ],
    midDensity: 5,
    near: ['fence', 'poles'],
    snowyWinter: false,
  },
  prairie: {
    ground: '#a9b25e',
    groundFar: '#bcc27a',
    shoulder: '#9d9d62',
    far: [far('hills', '#8d9a62', 0.12, 0.6)],
    mid: [
      ['wheat', 4],
      ['oak', 2],
      ['silo', 1],
      ['cattle', 2],
      ['haybale', 2],
      ['farmhouse', 1],
    ],
    midDensity: 6,
    near: ['fence', 'poles'],
    snowyWinter: false,
  },
  ozarks: {
    ground: '#6e8a4a',
    groundFar: '#7d9658',
    shoulder: '#8a8460',
    far: [far('ridges', '#58744f', 0.3, 0.6)],
    mid: [
      ['oak', 7],
      ['maple', 2],
      ['barn', 1],
      ['rock', 1],
    ],
    midDensity: 9,
    near: ['rail', 'grass'],
    snowyWinter: false,
  },
  farmland: {
    ground: '#8fae4f',
    groundFar: '#a3bb68',
    shoulder: '#8e9a5c',
    far: [far('flat', '#6e8a4c', 0.08, 0.6)],
    mid: [
      ['corn', 5],
      ['silo', 2],
      ['barn', 2],
      ['farmhouse', 1],
      ['water-tower', 1],
      ['oak', 2],
    ],
    midDensity: 6,
    near: ['fence', 'poles'],
    snowyWinter: true,
  },
  'great-lakes': {
    ground: '#8a9a6a',
    groundFar: '#9aa77c',
    shoulder: '#8d8d78',
    far: [far('water', '#6f9ab8', 0.04, 0.5), far('skyline', '#5f6774', 0.32, 0.7)],
    mid: [
      ['factory', 3],
      ['refinery', 1],
      ['oak', 2],
      ['billboard', 2],
      ['water-tower', 1],
    ],
    midDensity: 6,
    near: ['poles', 'rail'],
    snowyWinter: true,
  },
  appalachian: {
    ground: '#5f7f45',
    groundFar: '#6f8d58',
    shoulder: '#7d7a5c',
    far: [far('ridges', '#6c87a0', 0.5, 0.9), far('ridges', '#4f6c52', 0.35, 0.45)],
    mid: [
      ['maple', 4],
      ['oak', 4],
      ['church', 1],
      ['barn', 1],
      ['rock', 1],
    ],
    midDensity: 9,
    near: ['rail', 'rocks'],
    snowyWinter: true,
  },
  turnpike: {
    ground: '#7f9a55',
    groundFar: '#90a868',
    shoulder: '#868260',
    far: [far('ridges', '#5d7a5c', 0.3, 0.6)],
    mid: [
      ['barn', 2],
      ['silo', 2],
      ['farmhouse', 2],
      ['maple', 3],
      ['church', 1],
      ['corn', 2],
    ],
    midDensity: 7,
    near: ['fence', 'rail'],
    snowyWinter: true,
  },
  jersey: {
    ground: '#8c9466',
    groundFar: '#9ea377',
    shoulder: '#8a8a76',
    far: [far('skyline', '#6a7180', 0.4, 0.85)],
    mid: [
      ['refinery', 3],
      ['reeds', 4],
      ['billboard', 2],
      ['factory', 2],
    ],
    midDensity: 6,
    near: ['rail', 'poles'],
    snowyWinter: false,
  },
  manhattan: {
    ground: '#6f7073',
    groundFar: '#7c7d80',
    shoulder: '#77777a',
    far: [far('skyline', '#4f5664', 0.95, 0.6)],
    mid: [
      ['factory', 2],
      ['billboard', 3],
      ['water-tower', 2],
    ],
    midDensity: 7,
    near: ['rail', 'poles'],
    snowyWinter: false,
  },
  rockies: {
    ground: '#7a8a5a',
    groundFar: '#8a9a6c',
    shoulder: '#83806a',
    far: [far('snowpeaks', '#8e98b0', 0.85, 0.75, true), far('mountains', '#5f7258', 0.4, 0.3)],
    mid: [
      ['fir', 6],
      ['pine', 3],
      ['rock', 2],
    ],
    midDensity: 9,
    near: ['rail', 'rocks'],
    snowyWinter: true,
  },
  'red-rock': {
    ground: '#c47a4e',
    groundFar: '#d48f64',
    shoulder: '#b07454',
    far: [far('cliffs', '#b5583c', 0.55, 0.65), far('buttes', '#9c4c36', 0.3, 0.3)],
    mid: [
      ['spire', 2],
      ['rock', 3],
      ['sage', 4],
      ['mesquite', 1],
    ],
    midDensity: 5,
    near: ['fence', 'rocks'],
    snowyWinter: false,
  },
  'great-basin': {
    ground: '#b7ab83',
    groundFar: '#c6bc98',
    shoulder: '#a99f7c',
    far: [far('mountains', '#8f8aa0', 0.42, 0.8, true)],
    mid: [
      ['sage', 9],
      ['rock', 1],
      ['cattle', 1],
    ],
    midDensity: 6,
    near: ['fence', 'posts'],
    snowyWinter: true,
  },
  'deep-south': {
    ground: '#6f8f45',
    groundFar: '#7f9c58',
    shoulder: '#8a7d58',
    far: [far('flat', '#4d6b3a', 0.12, 0.5)],
    mid: [
      ['pine', 6],
      ['cotton', 2],
      ['oak', 2],
      ['church', 1],
      ['farmhouse', 1],
    ],
    midDensity: 8,
    near: ['poles', 'grass'],
    snowyWinter: false,
  },
  bayou: {
    ground: '#607d48',
    groundFar: '#728c58',
    shoulder: '#7a7a5c',
    far: [far('flat', '#4f6a44', 0.14, 0.5)],
    mid: [
      ['cypress', 6],
      ['reeds', 3],
      ['oak', 1],
    ],
    midDensity: 8,
    near: ['rail', 'grass'],
    snowyWinter: false,
  },
  piedmont: {
    ground: '#8a8a4c',
    groundFar: '#9c9a5e',
    shoulder: '#a5764f',
    far: [far('hills', '#5c7a50', 0.2, 0.55)],
    mid: [
      ['pine', 5],
      ['tobacco-barn', 2],
      ['oak', 3],
      ['farmhouse', 1],
    ],
    midDensity: 8,
    near: ['fence', 'poles'],
    snowyWinter: false,
  },
  florida: {
    ground: '#9bb35a',
    groundFar: '#adc070',
    shoulder: '#b9ae84',
    far: [far('flat', '#6f8f58', 0.07, 0.5)],
    mid: [
      ['fan-palm', 3],
      ['royal-palm', 2],
      ['orchard', 4],
      ['water-tower', 1],
      ['billboard', 1],
    ],
    midDensity: 6,
    near: ['poles', 'grass'],
    snowyWinter: false,
  },
  northwest: {
    ground: '#4f6e3c',
    groundFar: '#5f7e4e',
    shoulder: '#6f735e',
    far: [far('volcano', '#9aa8c0', 0.85, 0.9, true), far('ridges', '#3f5c43', 0.32, 0.35)],
    mid: [
      ['fir', 10],
      ['maple', 1],
    ],
    midDensity: 11,
    near: ['rail', 'grass'],
    snowyWinter: false,
  },
  sierra: {
    ground: '#6c7b52',
    groundFar: '#7c8a64',
    shoulder: '#7d7a68',
    far: [far('snowpeaks', '#8a95ad', 0.75, 0.75, true), far('ridges', '#4a6450', 0.35, 0.35)],
    mid: [
      ['fir', 6],
      ['pine', 3],
      ['rock', 2],
    ],
    midDensity: 9,
    near: ['rail', 'rocks'],
    snowyWinter: true,
  },
  'central-valley': {
    ground: '#a8b060',
    groundFar: '#b8be78',
    shoulder: '#a49f78',
    far: [far('hills', '#9b9f80', 0.15, 0.8)],
    mid: [
      ['orchard', 6],
      ['farmhouse', 1],
      ['water-tower', 1],
      ['fan-palm', 1],
    ],
    midDensity: 6,
    near: ['fence', 'poles'],
    snowyWinter: false,
  },
  'bay-area': {
    ground: '#9aa36a',
    groundFar: '#aab27c',
    shoulder: '#8f8e78',
    far: [far('hills', '#7f8f68', 0.35, 0.6), far('skyline', '#6f7684', 0.4, 0.8)],
    mid: [
      ['oak', 3],
      ['billboard', 2],
      ['fan-palm', 1],
    ],
    midDensity: 6,
    near: ['rail', 'poles'],
    snowyWinter: false,
  },
  'northern-plains': {
    ground: '#b4ad74',
    groundFar: '#c3bc8a',
    shoulder: '#a59f74',
    far: [far('badlands', '#a08a6c', 0.25, 0.65)],
    mid: [
      ['wheat', 5],
      ['elevator', 2],
      ['cattle', 2],
      ['haybale', 2],
    ],
    midDensity: 5,
    near: ['fence', 'poles'],
    snowyWinter: true,
  },
  northwoods: {
    ground: '#5f7f48',
    groundFar: '#6f8d58',
    shoulder: '#7d7a64',
    far: [far('flat', '#3f5a3c', 0.16, 0.5)],
    mid: [
      ['birch', 4],
      ['fir', 4],
      ['barn', 2],
      ['silo', 1],
    ],
    midDensity: 9,
    near: ['fence', 'grass'],
    snowyWinter: true,
  },
  'new-england': {
    ground: '#6f8a4c',
    groundFar: '#7f985c',
    shoulder: '#83806a',
    far: [far('hills', '#5f7558', 0.28, 0.55)],
    mid: [
      ['maple', 5],
      ['church', 2],
      ['stone-wall', 2],
      ['farmhouse', 2],
      ['birch', 1],
    ],
    midDensity: 8,
    near: ['rail', 'board-fence'],
    snowyWinter: true,
  },
  'mid-atlantic': {
    ground: '#7a9154',
    groundFar: '#8aa066',
    shoulder: '#86826a',
    far: [far('hills', '#617a5b', 0.22, 0.55)],
    mid: [
      ['oak', 5],
      ['farmhouse', 2],
      ['church', 1],
      ['barn', 1],
      ['billboard', 1],
    ],
    midDensity: 8,
    near: ['rail', 'poles'],
    snowyWinter: false,
  },
  'upland-south': {
    ground: '#7d9b4c',
    groundFar: '#8dab5e',
    shoulder: '#8a8460',
    far: [far('hills', '#62804f', 0.24, 0.55)],
    mid: [
      ['oak', 4],
      ['barn', 2],
      ['tobacco-barn', 1],
      ['farmhouse', 1],
      ['cattle', 1],
    ],
    midDensity: 7,
    near: ['board-fence', 'rail'],
    snowyWinter: false,
  },
};
